name: 'Build Koms'
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 'stable'
      - run: nimble check -Y
      - name: "Build koms binary"
        run: |
          cd komslib
          nimble develop
          cd ..
          nimble build -Y
          mv bin/koms* bin/${{matrix.os}}
      - uses: actions/upload-artifact@v2
        with:                                         
          name: Koms application   
          path: bin/${{matrix.os}}